# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Sample command that can be used for caching a whole folder at once
commands:
  cached-folder:
    description: "Conditionally cache a generated folder based on an input folder"
    parameters:
      lock-file:
        description: "Name of the generated lock file"
        type: string
      input-folder:
        description: "Input folder to SHA1 for the cache key"
        type: string
      output-folder:
        description: "Output folder to cache"
        type: string
      generate-command:
        description: "Command to execute in order to generate the output file"
        type: string

    steps:
      - run:
          name: Combine files to single file for the cache key
          command: |
            find << parameters.input-folder >> -type f | sort | xargs -n 10000000 sha256sum > << parameters.lock-file >>
            ls -lh << parameters.lock-file >>
            cat << parameters.lock-file >>

      - restore_cache:
          keys:
            - cache-dir-{{ checksum "<< parameters.lock-file >>" }}

      - run:
          name: Generate protos
          command: |
            ls -lh << parameters.output-folder >> >/dev/null 2>&1 || << parameters.generate-command >>

      - save_cache:
          key: cache-dir-{{ checksum "<< parameters.lock-file >>" }}
          paths:
            - << parameters.output-folder >>
